const prefix = 'INVERTER_INFO'
export const CHANGE_DATE_TYPE = prefix +  '/CHANGE_DATE_TYPE'
export const CHANGE_DATE_VALUE = prefix + '/CHANGE_DATE_VALUE'
export const CHANGE_FIELD = prefix + '/CHANGE_FIELD'
export const CHANGE_CHART_DATA = prefix + '/CHANGE_CHART_DATA'
export const CHANGE_TREE_DATA = prefix + '/CHANGE_TREE_DATA'
export const CHANGE_TREE_SELECT = prefix + '/CHANGE_TREE_SELECT'
export const CHANGE_PREVIEW_DATA = prefix + '/CHANGE_PREVIEW_DATA'